apiVersion: v1
kind: Namespace
metadata:
  name: practica2-201549059
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-deployment
  namespace: practica2-201549059
  labels:
    app: grpc-deployment
spec:
  selector:
    matchLabels:
      app: grpc-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: grpc-deployment
    spec:
      hostname: grpc-pod-host
      containers:
        - name: grpc-client-api
          image: davidlux123/api-grpc-client
          env:
          - name: GRPC_SERVER_HOST
            value: grpc-pod-host
          - name: GRPC_SERVER_PORT
            value: '50051'
          ports:
            - containerPort: 3000
        - name: grpc-server
          image: davidlux123/producer-kafka-grpc-server 
          env:
          - name: KAFKA_HOST
            value: my-cluster-kafka-bootstrap.kafka
          - name: KAFKA_PORT
            value: '9092'
          ports:
            - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: svc-grpc
  namespace: practica2-201549059
  labels:
    app: grpc-deployment
spec:
  type: LoadBalancer
  selector:
    app: grpc-deployment
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
