// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IngressGameClient is the client API for IngressGame service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IngressGameClient interface {
	SendResultGame(ctx context.Context, in *GameRequest, opts ...grpc.CallOption) (*GameReply, error)
}

type ingressGameClient struct {
	cc grpc.ClientConnInterface
}

func NewIngressGameClient(cc grpc.ClientConnInterface) IngressGameClient {
	return &ingressGameClient{cc}
}

func (c *ingressGameClient) SendResultGame(ctx context.Context, in *GameRequest, opts ...grpc.CallOption) (*GameReply, error) {
	out := new(GameReply)
	err := c.cc.Invoke(ctx, "/games.IngressGame/SendResultGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IngressGameServer is the server API for IngressGame service.
// All implementations must embed UnimplementedIngressGameServer
// for forward compatibility
type IngressGameServer interface {
	SendResultGame(context.Context, *GameRequest) (*GameReply, error)
	mustEmbedUnimplementedIngressGameServer()
}

// UnimplementedIngressGameServer must be embedded to have forward compatible implementations.
type UnimplementedIngressGameServer struct {
}

func (UnimplementedIngressGameServer) SendResultGame(context.Context, *GameRequest) (*GameReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendResultGame not implemented")
}
func (UnimplementedIngressGameServer) mustEmbedUnimplementedIngressGameServer() {}

// UnsafeIngressGameServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IngressGameServer will
// result in compilation errors.
type UnsafeIngressGameServer interface {
	mustEmbedUnimplementedIngressGameServer()
}

func RegisterIngressGameServer(s grpc.ServiceRegistrar, srv IngressGameServer) {
	s.RegisterService(&IngressGame_ServiceDesc, srv)
}

func _IngressGame_SendResultGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngressGameServer).SendResultGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/games.IngressGame/SendResultGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngressGameServer).SendResultGame(ctx, req.(*GameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IngressGame_ServiceDesc is the grpc.ServiceDesc for IngressGame service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IngressGame_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "games.IngressGame",
	HandlerType: (*IngressGameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendResultGame",
			Handler:    _IngressGame_SendResultGame_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/games.proto",
}
